### ISSUE TITLE
don't see Magento Connector in Modules

### ISSUE THREAD

**Issue by Top-CMS** [OCA/connector-ecommerce#30]
Hi, 

Just installed Odoo 9.0, and followed the steps on http://odoo-magento-connector.com/guides/installation_guide.html#installation

But after editing the openerp-server.conf and add the
<code>
addons_path = /usr/lib/python2.7/dist-packages/openerp/addons,/usr/lib/python2.7/dist-packages/openerp/addons/ocr/connector,/usr/lib/python2.7/dist-packages/openerp/addons/ocr/connector-ecommerce,/usr/lib/python2.7/dist-packages/openerp/addons/ocr/connector-magento,/usr/lib/python2.7/dist-packages/openerp/addons/ocr/e-commerce,/usr/lib/python2.7/dist-packages/openerp/addons/ocr/product-attribute,/usr/lib/python2.7/dist-packages/openerp/addons/ocr/sale-workflow
</code>
then reboot and search for any magento connector, nothing will apear

what am i missing in this, to install the  magento connector

**Comment by parthivgls** [comment]
@Top-CMS Magento modules are yet to be migrated to v9, that's the reason their "install" flag is set to false and modules are not visible in "modules list".
