### ISSUE TITLE
[8.0] Could not find the module sale_payment_method_automatic_workflow in the repo "e-commerce" (branch 8.0)

### ISSUE THREAD

**Issue by tungocbui** [OCA/connector-ecommerce#31]
When trying to install the module "connector_ecommerce", i got the error below

except_orm: (u'Error', u"You try to install module 'connector_ecommerce' that depends on module 'sale_payment_method_automatic_workflow'.\nBut the latter module is not available in your system.")

I tried to take a look at the list of modules in the repository "OCA / e-commerce" and i could not find that module in the branch 8.0, that module is exist in the branch 9.0. Which is weird, because the ["pull request"](https://github.com/OCA/e-commerce/pull/34) contain that module was for the branch 8.0.

Have a nice day

**Comment by guewen** [comment]
Hi,

It has been moved in the OCA/sale-workflow project, you'll find it here: https://github.com/OCA/sale-workflow/tree/8.0

Have a nice day too!

**Comment by tungocbui** [comment]
Thks for your very quick answer...
