### ISSUE TITLE
issue when I install connector-ecommerce on OpenERP v7

### ISSUE THREAD

**Issue by AMhadhbi** [OCA/connector-ecommerce#46]
res_id = model_obj.create(cr, uid, values, context=context)

  File "/opt/openerp/htdocs/openerp/addons/base/ir/ir_ui_view.py", line 103, in create

    return super(view, self).create(cr, uid, values, context)

  File "/opt/openerp/submodules/****connector/connector/producer.py**", line 44, in create**

    record_id = create_original(self, cr, uid, vals, context=context)

  File "/opt/openerp/htdocs/openerp/osv/orm.py", line 4596, in create

    self._validate(cr, user, [id_new], context)

  File "/opt/openerp/htdocs/openerp/osv/orm.py", line 1577, in _validate

    raise except_orm('ValidateError', '\n'.join(error_msgs))

except_osv: ('ValidateError', u'Error occurred while validating the field(s) arch: Invalid XML for View Architecture!')

**Comment by pedrobaeza** [comment]
That version is very old, but it's working without bug since long, so you have for sure something incorrect in your DB. Try it in a fresh DB.

**Comment by AMhadhbi** [comment]
@pedrobaeza yes it is very old version. I want to install magento-connector on OpenERP7 and sure I install it in a fresh DB. so I have this issue in fresh DB and I checked this error when I install connector-ecommerce.
