### ISSUE TITLE
Missing env variable in openupgrade method call for migration to version 14

### ISSUE THREAD

**Issue by StephaneMangin** [OCA/connector-ecommerce#69]
There is an API call issue in the migration script to version 14.

## Module
connector_ecormmerce

## Describe the bug
Missing 'env' variable in openupgrade method call.

## To Reproduce
Migrate module from previous version to 14.0

**Expected behavior**
The migration should pass without API call errors

**Comment by StephaneMangin** [comment]
PR here : https://github.com/OCA/connector-ecommerce/pull/68

**Comment by pedrobaeza** [comment]
No need to open issue when you put a PR
